import { GoogleTagManager } from "@next/third-parties/google";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const { NEXT_PUBLIC_GA_MEASUREMENT_ID } = process.env;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>

      {NEXT_PUBLIC_GA_MEASUREMENT_ID && (
        <GoogleTagManager gtmId={NEXT_PUBLIC_GA_MEASUREMENT_ID} />
      )}
    </html>
  );
}
